{
  level: 'error',
  message: null,
  service: 'user-service',
  timestamp: '2021-11-24T18:06:13.565Z'
}
{
  level: 'info',
  message: { File_Name: 'test4' },
  service: 'user-service',
  timestamp: '2021-11-24T18:06:17.243Z'
}
{
  level: 'error',
  message: Error: Access denied for user 'root'@'localhost' (using password: YES)
      at Packet.asError (C:\Users\DELL\Desktop\Advanced draft\AdvancedSeE\dbmanager\node_modules\mysql2\lib\packets\packet.js:728:17)
      at ClientHandshake.execute (C:\Users\DELL\Desktop\Advanced draft\AdvancedSeE\dbmanager\node_modules\mysql2\lib\commands\command.js:29:26)
      at Connection.handlePacket (C:\Users\DELL\Desktop\Advanced draft\AdvancedSeE\dbmanager\node_modules\mysql2\lib\connection.js:456:32)
      at PacketParser.onPacket (C:\Users\DELL\Desktop\Advanced draft\AdvancedSeE\dbmanager\node_modules\mysql2\lib\connection.js:85:12)
      at PacketParser.executeStart (C:\Users\DELL\Desktop\Advanced draft\AdvancedSeE\dbmanager\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (C:\Users\DELL\Desktop\Advanced draft\AdvancedSeE\dbmanager\node_modules\mysql2\lib\connection.js:92:25)
      at Socket.emit (node:events:329:20)
      at addChunk (node:internal/streams/readable:304:12)
      at readableAddChunk (node:internal/streams/readable:279:9)
      at Socket.Readable.push (node:internal/streams/readable:218:10) {
    code: 'ER_ACCESS_DENIED_ERROR',
    errno: 1045,
    sqlState: '28000',
    sqlMessage: "Access denied for user 'root'@'localhost' (using password: YES)",
    sql: undefined
  },
  service: 'user-service',
  timestamp: '2021-11-24T18:14:50.939Z'
}
{
  level: 'error',
  message: null,
  service: 'user-service',
  timestamp: '2021-12-10T09:40:11.136Z'
}
{
  level: 'error',
  message: null,
  service: 'user-service',
  timestamp: '2021-12-10T09:40:11.140Z'
}
{
  level: 'error',
  message: null,
  service: 'user-service',
  timestamp: '2021-12-10T09:40:11.140Z'
}
{
  level: 'error',
  message: Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-1639129250658
              (File_ID INT NOT NULL AUTO_INCREMENT,  
              F' at line 1
      at Packet.asError (C:\Users\DELL\Desktop\New folder (4)\AdvancedSeE\dbmanager\node_modules\mysql2\lib\packets\packet.js:728:17)
      at Query.execute (C:\Users\DELL\Desktop\New folder (4)\AdvancedSeE\dbmanager\node_modules\mysql2\lib\commands\command.js:29:26)
      at Connection.handlePacket (C:\Users\DELL\Desktop\New folder (4)\AdvancedSeE\dbmanager\node_modules\mysql2\lib\connection.js:456:32)
      at PacketParser.onPacket (C:\Users\DELL\Desktop\New folder (4)\AdvancedSeE\dbmanager\node_modules\mysql2\lib\connection.js:85:12)
      at PacketParser.executeStart (C:\Users\DELL\Desktop\New folder (4)\AdvancedSeE\dbmanager\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (C:\Users\DELL\Desktop\New folder (4)\AdvancedSeE\dbmanager\node_modules\mysql2\lib\connection.js:92:25)
      at Socket.emit (node:events:329:20)
      at addChunk (node:internal/streams/readable:304:12)
      at readableAddChunk (node:internal/streams/readable:279:9)
      at Socket.Readable.push (node:internal/streams/readable:218:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:192:23) {
    code: 'ER_PARSE_ERROR',
    errno: 1064,
    sqlState: '42000',
    sqlMessage: "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-1639129250658\n" +
      '            (File_ID INT NOT NULL AUTO_INCREMENT,  \n' +
      "            F' at line 1",
    sql: 'CREATE TABLE uploadfile-1639129250658\n' +
      '            (File_ID INT NOT NULL AUTO_INCREMENT,  \n' +
      '            File_Name VARCHAR(50),\n' +
      '            PRIMARY KEY(File_ID)\n' +
      '            )'
  },
  service: 'user-service',
  timestamp: '2021-12-10T09:40:50.749Z'
}
{
  level: 'error',
  message: null,
  service: 'user-service',
  timestamp: '2021-12-10T09:47:38.047Z'
}
{
  level: 'error',
  message: null,
  service: 'user-service',
  timestamp: '2021-12-10T09:47:38.050Z'
}
{
  level: 'error',
  message: null,
  service: 'user-service',
  timestamp: '2021-12-10T09:47:38.050Z'
}
{
  level: 'error',
  message: Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-1639129670245
              (File_ID INT NOT NULL AUTO_INCREMENT,  
              F' at line 1
      at Packet.asError (C:\Users\DELL\Desktop\New folder (4)\AdvancedSeE\dbmanager\node_modules\mysql2\lib\packets\packet.js:728:17)
      at Query.execute (C:\Users\DELL\Desktop\New folder (4)\AdvancedSeE\dbmanager\node_modules\mysql2\lib\commands\command.js:29:26)
      at Connection.handlePacket (C:\Users\DELL\Desktop\New folder (4)\AdvancedSeE\dbmanager\node_modules\mysql2\lib\connection.js:456:32)
      at PacketParser.onPacket (C:\Users\DELL\Desktop\New folder (4)\AdvancedSeE\dbmanager\node_modules\mysql2\lib\connection.js:85:12)
      at PacketParser.executeStart (C:\Users\DELL\Desktop\New folder (4)\AdvancedSeE\dbmanager\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (C:\Users\DELL\Desktop\New folder (4)\AdvancedSeE\dbmanager\node_modules\mysql2\lib\connection.js:92:25)
      at Socket.emit (node:events:329:20)
      at addChunk (node:internal/streams/readable:304:12)
      at readableAddChunk (node:internal/streams/readable:279:9)
      at Socket.Readable.push (node:internal/streams/readable:218:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:192:23) {
    code: 'ER_PARSE_ERROR',
    errno: 1064,
    sqlState: '42000',
    sqlMessage: "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-1639129670245\n" +
      '            (File_ID INT NOT NULL AUTO_INCREMENT,  \n' +
      "            F' at line 1",
    sql: 'CREATE TABLE uploadfile-1639129670245\n' +
      '            (File_ID INT NOT NULL AUTO_INCREMENT,  \n' +
      '            File_Name VARCHAR(50),\n' +
      '            PRIMARY KEY(File_ID)\n' +
      '            )'
  },
  service: 'user-service',
  timestamp: '2021-12-10T09:47:50.387Z'
}
{
  level: 'error',
  message: null,
  service: 'user-service',
  timestamp: '2021-12-10T09:53:38.149Z'
}
{
  level: 'error',
  message: null,
  service: 'user-service',
  timestamp: '2021-12-10T09:53:38.152Z'
}
{
  level: 'error',
  message: null,
  service: 'user-service',
  timestamp: '2021-12-10T09:53:38.152Z'
}
{
  level: 'info',
  message: 'get files from db',
  service: 'user-service',
  timestamp: '2021-12-10T09:53:56.731Z'
}
{
  level: 'error',
  message: null,
  service: 'user-service',
  timestamp: '2021-12-10T09:53:56.736Z'
}
{
  level: 'error',
  message: null,
  service: 'user-service',
  timestamp: '2021-12-10T09:54:29.843Z'
}
{
  level: 'error',
  message: null,
  service: 'user-service',
  timestamp: '2021-12-10T09:54:29.846Z'
}
{
  level: 'error',
  message: null,
  service: 'user-service',
  timestamp: '2021-12-10T09:54:29.846Z'
}
{
  level: 'info',
  message: 'get files from db',
  service: 'user-service',
  timestamp: '2021-12-10T09:54:36.235Z'
}
{
  level: 'error',
  message: Error: Can't add new command when connection is in closed state
      at Connection._addCommandClosedState (C:\Users\DELL\Desktop\New folder (4)\AdvancedSeE\dbmanager\node_modules\mysql2\lib\connection.js:148:17)
      at Connection.query (C:\Users\DELL\Desktop\New folder (4)\AdvancedSeE\dbmanager\node_modules\mysql2\lib\connection.js:546:17)
      at C:\Users\DELL\Desktop\New folder (4)\AdvancedSeE\dbmanager\index.js:36:8
      at Layer.handle [as handle_request] (C:\Users\DELL\Desktop\New folder (4)\AdvancedSeE\dbmanager\node_modules\express\lib\router\layer.js:95:5)
      at next (C:\Users\DELL\Desktop\New folder (4)\AdvancedSeE\dbmanager\node_modules\express\lib\router\route.js:137:13)
      at Route.dispatch (C:\Users\DELL\Desktop\New folder (4)\AdvancedSeE\dbmanager\node_modules\express\lib\router\route.js:112:3)
      at Layer.handle [as handle_request] (C:\Users\DELL\Desktop\New folder (4)\AdvancedSeE\dbmanager\node_modules\express\lib\router\layer.js:95:5)
      at C:\Users\DELL\Desktop\New folder (4)\AdvancedSeE\dbmanager\node_modules\express\lib\router\index.js:281:22
      at Function.process_params (C:\Users\DELL\Desktop\New folder (4)\AdvancedSeE\dbmanager\node_modules\express\lib\router\index.js:335:12)
      at next (C:\Users\DELL\Desktop\New folder (4)\AdvancedSeE\dbmanager\node_modules\express\lib\router\index.js:275:10)
      at C:\Users\DELL\Desktop\New folder (4)\AdvancedSeE\dbmanager\node_modules\express\lib\router\index.js:635:15
      at next (C:\Users\DELL\Desktop\New folder (4)\AdvancedSeE\dbmanager\node_modules\express\lib\router\index.js:260:14)
      at Function.handle (C:\Users\DELL\Desktop\New folder (4)\AdvancedSeE\dbmanager\node_modules\express\lib\router\index.js:174:3)
      at router (C:\Users\DELL\Desktop\New folder (4)\AdvancedSeE\dbmanager\node_modules\express\lib\router\index.js:47:12)
      at Layer.handle [as handle_request] (C:\Users\DELL\Desktop\New folder (4)\AdvancedSeE\dbmanager\node_modules\express\lib\router\layer.js:95:5)
      at trim_prefix (C:\Users\DELL\Desktop\New folder (4)\AdvancedSeE\dbmanager\node_modules\express\lib\router\index.js:317:13) {
    fatal: true
  },
  service: 'user-service',
  timestamp: '2021-12-10T09:54:36.242Z'
}
{
  level: 'error',
  message: null,
  service: 'user-service',
  timestamp: '2021-12-10T10:03:13.713Z'
}
{
  level: 'error',
  message: null,
  service: 'user-service',
  timestamp: '2021-12-10T10:03:13.716Z'
}
{
  level: 'error',
  message: null,
  service: 'user-service',
  timestamp: '2021-12-10T10:03:13.716Z'
}
{
  level: 'info',
  message: 'get files from db',
  service: 'user-service',
  timestamp: '2021-12-10T10:03:21.471Z'
}
{
  level: 'error',
  message: null,
  service: 'user-service',
  timestamp: '2021-12-10T10:03:21.475Z'
}
{
  level: 'error',
  message: null,
  service: 'user-service',
  timestamp: '2021-12-10T10:47:11.288Z'
}
{
  level: 'error',
  message: null,
  service: 'user-service',
  timestamp: '2021-12-10T10:47:11.292Z'
}
{
  level: 'error',
  message: null,
  service: 'user-service',
  timestamp: '2021-12-10T10:47:11.293Z'
}
{
  level: 'info',
  message: 'get files from db',
  service: 'user-service',
  timestamp: '2021-12-10T10:47:52.536Z'
}
{
  level: 'error',
  message: Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '{File_Path}' at line 1
      at Packet.asError (C:\Users\DELL\Desktop\New folder (4)\AdvancedSeE\dbmanager\node_modules\mysql2\lib\packets\packet.js:728:17)
      at Query.execute (C:\Users\DELL\Desktop\New folder (4)\AdvancedSeE\dbmanager\node_modules\mysql2\lib\commands\command.js:29:26)
      at Connection.handlePacket (C:\Users\DELL\Desktop\New folder (4)\AdvancedSeE\dbmanager\node_modules\mysql2\lib\connection.js:456:32)
      at PacketParser.onPacket (C:\Users\DELL\Desktop\New folder (4)\AdvancedSeE\dbmanager\node_modules\mysql2\lib\connection.js:85:12)
      at PacketParser.executeStart (C:\Users\DELL\Desktop\New folder (4)\AdvancedSeE\dbmanager\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (C:\Users\DELL\Desktop\New folder (4)\AdvancedSeE\dbmanager\node_modules\mysql2\lib\connection.js:92:25)
      at Socket.emit (node:events:329:20)
      at addChunk (node:internal/streams/readable:304:12)
      at readableAddChunk (node:internal/streams/readable:279:9)
      at Socket.Readable.push (node:internal/streams/readable:218:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:192:23) {
    code: 'ER_PARSE_ERROR',
    errno: 1064,
    sqlState: '42000',
    sqlMessage: "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '{File_Path}' at line 1",
    sql: 'SELECT * FROM ${File_Path}'
  },
  service: 'user-service',
  timestamp: '2021-12-10T10:47:52.539Z'
}
{
  level: 'error',
  message: null,
  service: 'user-service',
  timestamp: '2021-12-10T12:31:56.189Z'
}
{
  level: 'error',
  message: null,
  service: 'user-service',
  timestamp: '2021-12-10T12:31:56.197Z'
}
{
  level: 'error',
  message: null,
  service: 'user-service',
  timestamp: '2021-12-10T12:31:56.199Z'
}
{
  level: 'error',
  message: null,
  service: 'user-service',
  timestamp: '2021-12-09T18:27:04.812Z'
}
{
  level: 'error',
  message: null,
  service: 'user-service',
  timestamp: '2021-12-09T18:27:04.815Z'
}
{
  level: 'error',
  message: null,
  service: 'user-service',
  timestamp: '2021-12-09T18:38:44.663Z'
}
{
  level: 'error',
  message: null,
  service: 'user-service',
  timestamp: '2021-12-09T18:38:44.676Z'
}
{
  level: 'error',
  message: Error: connect ETIMEDOUT
      at Connection._handleTimeoutError (C:\Users\DELL\Desktop\ADV PROJECT\AdvancedSeE\dbmanager\node_modules\mysql2\lib\connection.js:189:17)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7) {
    errorno: 'ETIMEDOUT',
    code: 'ETIMEDOUT',
    syscall: 'connect',
    fatal: true
  },
  service: 'user-service',
  timestamp: '2021-12-10T09:50:31.257Z'
}
{
  level: 'error',
  message: Error: connect ETIMEDOUT
      at Connection._handleTimeoutError (C:\Users\DELL\Desktop\ADV PROJECT\AdvancedSeE\dbmanager\node_modules\mysql2\lib\connection.js:189:17)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7) {
    errorno: 'ETIMEDOUT',
    code: 'ETIMEDOUT',
    syscall: 'connect',
    fatal: true
  },
  service: 'user-service',
  timestamp: '2021-12-10T09:50:31.374Z'
}
{
  level: 'error',
  message: 'connect ETIMEDOUT',
  service: 'user-service',
  timestamp: '2021-12-10T09:50:31.376Z'
}
{
  level: 'error',
  message: Error: Can't add new command when connection is in closed state
      at Connection._addCommandClosedState (C:\Users\DELL\Desktop\ADV PROJECT\AdvancedSeE\dbmanager\node_modules\mysql2\lib\connection.js:148:17)
      at Connection.query (C:\Users\DELL\Desktop\ADV PROJECT\AdvancedSeE\dbmanager\node_modules\mysql2\lib\connection.js:546:17)
      at readCsvFile (C:\Users\DELL\Desktop\ADV PROJECT\AdvancedSeE\dbmanager\ImportCSVFile\CSVtoDb.js:39:16) {
    fatal: true
  },
  service: 'user-service',
  timestamp: '2021-12-10T09:50:31.571Z'
}
{
  level: 'error',
  message: Error: read ECONNRESET
      at TCP.onStreamRead (internal/stream_base_commons.js:209:20) {
    errno: -4077,
    code: 'ECONNRESET',
    syscall: 'read',
    fatal: true
  },
  service: 'user-service',
  timestamp: '2021-12-10T09:51:59.730Z'
}
{
  level: 'error',
  message: null,
  service: 'user-service',
  timestamp: '2021-12-10T09:54:35.060Z'
}
{
  level: 'error',
  message: null,
  service: 'user-service',
  timestamp: '2021-12-10T09:54:35.070Z'
}
{
  level: 'info',
  message: {
    user_password: 'yyyyy44d',
    user_Email: 'ghaidaashtayeh99@gmail.com',
    db_Name: 'db'
  },
  service: 'user-service',
  timestamp: '2021-12-10T09:54:48.266Z'
}
{
  level: 'error',
  message: Error: Can't add new command when connection is in closed state
      at PromiseConnection.execute (C:\Users\DELL\Desktop\ADV PROJECT\AdvancedSeE\dbmanager\node_modules\mysql2\promise.js:111:22)
      at exports.login (C:\Users\DELL\Desktop\ADV PROJECT\AdvancedSeE\dbmanager\controllers\loginController.js:16:34)
      at Layer.handle [as handle_request] (C:\Users\DELL\Desktop\ADV PROJECT\AdvancedSeE\dbmanager\node_modules\express\lib\router\layer.js:95:5)
      at next (C:\Users\DELL\Desktop\ADV PROJECT\AdvancedSeE\dbmanager\node_modules\express\lib\router\route.js:137:13)
      at middleware (C:\Users\DELL\Desktop\ADV PROJECT\AdvancedSeE\dbmanager\node_modules\express-validator\src\middlewares\check.js:16:13)
      at processTicksAndRejections (internal/process/task_queues.js:93:5) {
    code: undefined,
    errno: undefined,
    sql: undefined,
    sqlState: undefined,
    sqlMessage: undefined
  },
  service: 'user-service',
  timestamp: '2021-12-10T09:54:48.268Z'
}
{
  level: 'error',
  message: null,
  service: 'user-service',
  timestamp: '2021-12-10T10:01:11.557Z'
}
{
  level: 'error',
  message: null,
  service: 'user-service',
  timestamp: '2021-12-10T10:01:11.568Z'
}
{
  level: 'info',
  message: {
    user_password: 'yyyyy44d',
    user_Email: 'ghaidaashtayeh99@gmail.com',
    db_Name: 'db'
  },
  service: 'user-service',
  timestamp: '2021-12-10T10:01:15.418Z'
}
{
  level: 'error',
  message: Error: Can't add new command when connection is in closed state
      at PromiseConnection.execute (C:\Users\DELL\Desktop\ADV PROJECT\AdvancedSeE\dbmanager\node_modules\mysql2\promise.js:111:22)
      at exports.login (C:\Users\DELL\Desktop\ADV PROJECT\AdvancedSeE\dbmanager\controllers\loginController.js:16:34)
      at Layer.handle [as handle_request] (C:\Users\DELL\Desktop\ADV PROJECT\AdvancedSeE\dbmanager\node_modules\express\lib\router\layer.js:95:5)
      at next (C:\Users\DELL\Desktop\ADV PROJECT\AdvancedSeE\dbmanager\node_modules\express\lib\router\route.js:137:13)
      at middleware (C:\Users\DELL\Desktop\ADV PROJECT\AdvancedSeE\dbmanager\node_modules\express-validator\src\middlewares\check.js:16:13)
      at processTicksAndRejections (internal/process/task_queues.js:93:5) {
    code: undefined,
    errno: undefined,
    sql: undefined,
    sqlState: undefined,
    sqlMessage: undefined
  },
  service: 'user-service',
  timestamp: '2021-12-10T10:01:15.418Z'
}
{
  level: 'info',
  message: {
    user_password: 'yyyyy44d',
    user_Email: 'ghaidaashtayeh99@gmail.com',
    db_Name: 'db'
  },
  service: 'user-service',
  timestamp: '2021-12-10T10:01:17.146Z'
}
{
  level: 'error',
  message: Error: Can't add new command when connection is in closed state
      at PromiseConnection.execute (C:\Users\DELL\Desktop\ADV PROJECT\AdvancedSeE\dbmanager\node_modules\mysql2\promise.js:111:22)
      at exports.login (C:\Users\DELL\Desktop\ADV PROJECT\AdvancedSeE\dbmanager\controllers\loginController.js:16:34)
      at Layer.handle [as handle_request] (C:\Users\DELL\Desktop\ADV PROJECT\AdvancedSeE\dbmanager\node_modules\express\lib\router\layer.js:95:5)
      at next (C:\Users\DELL\Desktop\ADV PROJECT\AdvancedSeE\dbmanager\node_modules\express\lib\router\route.js:137:13)
      at middleware (C:\Users\DELL\Desktop\ADV PROJECT\AdvancedSeE\dbmanager\node_modules\express-validator\src\middlewares\check.js:16:13)
      at processTicksAndRejections (internal/process/task_queues.js:93:5) {
    code: undefined,
    errno: undefined,
    sql: undefined,
    sqlState: undefined,
    sqlMessage: undefined
  },
  service: 'user-service',
  timestamp: '2021-12-10T10:01:17.149Z'
}
{
  level: 'error',
  message: null,
  service: 'user-service',
  timestamp: '2021-12-10T10:03:26.158Z'
}
{
  level: 'error',
  message: null,
  service: 'user-service',
  timestamp: '2021-12-10T10:03:26.164Z'
}
{
  level: 'info',
  message: {
    user_password: 'yyyyy44d',
    user_Email: 'ghaidaashtayeh99@gmail.com',
    db_Name: 'db'
  },
  service: 'user-service',
  timestamp: '2021-12-10T10:03:39.990Z'
}
{
  level: 'error',
  message: Error: Can't add new command when connection is in closed state
      at PromiseConnection.execute (C:\Users\DELL\Desktop\ADV PROJECT\AdvancedSeE\dbmanager\node_modules\mysql2\promise.js:111:22)
      at exports.login (C:\Users\DELL\Desktop\ADV PROJECT\AdvancedSeE\dbmanager\controllers\loginController.js:16:34)
      at Layer.handle [as handle_request] (C:\Users\DELL\Desktop\ADV PROJECT\AdvancedSeE\dbmanager\node_modules\express\lib\router\layer.js:95:5)
      at next (C:\Users\DELL\Desktop\ADV PROJECT\AdvancedSeE\dbmanager\node_modules\express\lib\router\route.js:137:13)
      at middleware (C:\Users\DELL\Desktop\ADV PROJECT\AdvancedSeE\dbmanager\node_modules\express-validator\src\middlewares\check.js:16:13)
      at processTicksAndRejections (internal/process/task_queues.js:93:5) {
    code: undefined,
    errno: undefined,
    sql: undefined,
    sqlState: undefined,
    sqlMessage: undefined
  },
  service: 'user-service',
  timestamp: '2021-12-10T10:03:39.991Z'
}
{
  level: 'error',
  message: null,
  service: 'user-service',
  timestamp: '2021-12-10T10:04:05.160Z'
}
{
  level: 'error',
  message: null,
  service: 'user-service',
  timestamp: '2021-12-10T10:04:05.166Z'
}
{
  level: 'error',
  message: null,
  service: 'user-service',
  timestamp: '2021-12-10T10:05:46.938Z'
}
{
  level: 'error',
  message: null,
  service: 'user-service',
  timestamp: '2021-12-10T10:05:46.950Z'
}
{
  level: 'error',
  message: null,
  service: 'user-service',
  timestamp: '2021-12-10T12:14:49.388Z'
}
{
  level: 'error',
  message: null,
  service: 'user-service',
  timestamp: '2021-12-10T12:14:49.405Z'
}
{
  level: 'error',
<<<<<<< HEAD
  message: null,
  service: 'user-service',
  timestamp: '2021-12-10T12:40:09.261Z'
=======
  message: Error: Access denied for user 'root'@'localhost' (using password: YES)
      at Packet.asError (C:\Users\DELL\Desktop\New folder (4)\AdvancedSeE\dbmanager\node_modules\mysql2\lib\packets\packet.js:728:17)
      at ClientHandshake.execute (C:\Users\DELL\Desktop\New folder (4)\AdvancedSeE\dbmanager\node_modules\mysql2\lib\commands\command.js:29:26)
      at Connection.handlePacket (C:\Users\DELL\Desktop\New folder (4)\AdvancedSeE\dbmanager\node_modules\mysql2\lib\connection.js:456:32)
      at PacketParser.onPacket (C:\Users\DELL\Desktop\New folder (4)\AdvancedSeE\dbmanager\node_modules\mysql2\lib\connection.js:85:12)
      at PacketParser.executeStart (C:\Users\DELL\Desktop\New folder (4)\AdvancedSeE\dbmanager\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (C:\Users\DELL\Desktop\New folder (4)\AdvancedSeE\dbmanager\node_modules\mysql2\lib\connection.js:92:25)
      at Socket.emit (node:events:329:20)
      at addChunk (node:internal/streams/readable:304:12)
      at readableAddChunk (node:internal/streams/readable:279:9)
      at Socket.Readable.push (node:internal/streams/readable:218:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:192:23) {
    code: 'ER_ACCESS_DENIED_ERROR',
    errno: 1045,
    sqlState: '28000',
    sqlMessage: "Access denied for user 'root'@'localhost' (using password: YES)",
    sql: undefined
  },
  service: 'user-service',
  timestamp: '2021-12-10T12:46:29.949Z'
>>>>>>> 4b8da8a9b3a836dedfa368ac61be60943c1488d6
}
{
  level: 'error',
  message: null,
  service: 'user-service',
<<<<<<< HEAD
  timestamp: '2021-12-10T12:40:09.299Z'
=======
  timestamp: '2021-12-10T12:46:49.074Z'
>>>>>>> 4b8da8a9b3a836dedfa368ac61be60943c1488d6
}
{
  level: 'error',
  message: null,
  service: 'user-service',
<<<<<<< HEAD
  timestamp: '2021-12-10T12:56:23.784Z'
=======
  timestamp: '2021-12-10T12:46:49.080Z'
>>>>>>> 4b8da8a9b3a836dedfa368ac61be60943c1488d6
}
{
  level: 'error',
  message: null,
  service: 'user-service',
<<<<<<< HEAD
  timestamp: '2021-12-10T12:56:23.806Z'
=======
  timestamp: '2021-12-10T12:46:49.080Z'
>>>>>>> 4b8da8a9b3a836dedfa368ac61be60943c1488d6
}
{
  level: 'error',
  message: Error: Access denied for user 'root'@'localhost' (using password: YES)
      at Packet.asError (C:\Users\DELL\Desktop\ADV PROJECT\AdvancedSeE\dbmanager\node_modules\mysql2\lib\packets\packet.js:728:17)
      at ClientHandshake.execute (C:\Users\DELL\Desktop\ADV PROJECT\AdvancedSeE\dbmanager\node_modules\mysql2\lib\commands\command.js:29:26)
      at Connection.handlePacket (C:\Users\DELL\Desktop\ADV PROJECT\AdvancedSeE\dbmanager\node_modules\mysql2\lib\connection.js:456:32)
      at PacketParser.onPacket (C:\Users\DELL\Desktop\ADV PROJECT\AdvancedSeE\dbmanager\node_modules\mysql2\lib\connection.js:85:12)
      at PacketParser.executeStart (C:\Users\DELL\Desktop\ADV PROJECT\AdvancedSeE\dbmanager\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (C:\Users\DELL\Desktop\ADV PROJECT\AdvancedSeE\dbmanager\node_modules\mysql2\lib\connection.js:92:25)
      at Socket.emit (events.js:315:20)
      at addChunk (internal/streams/readable.js:309:12)
      at readableAddChunk (internal/streams/readable.js:284:9)
      at Socket.Readable.push (internal/streams/readable.js:223:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
    code: 'ER_ACCESS_DENIED_ERROR',
    errno: 1045,
    sqlState: '28000',
    sqlMessage: "Access denied for user 'root'@'localhost' (using password: YES)",
    sql: undefined
  },
  service: 'user-service',
  timestamp: '2021-12-10T13:00:29.815Z'
}
{
  level: 'error',
  message: null,
  service: 'user-service',
  timestamp: '2021-12-10T13:00:59.150Z'
}
{
  level: 'error',
  message: null,
  service: 'user-service',
  timestamp: '2021-12-10T13:00:59.170Z'
}
{
  level: 'error',
  message: null,
  service: 'user-service',
  timestamp: '2021-12-10T13:00:59.173Z'
}
{
  level: 'error',
  message: null,
  service: 'user-service',
  timestamp: '2021-12-11T15:51:30.258Z'
}
{
  level: 'error',
  message: null,
  service: 'user-service',
  timestamp: '2021-12-11T15:51:30.277Z'
}
{
  level: 'error',
  message: null,
  service: 'user-service',
  timestamp: '2021-12-11T15:51:30.279Z'
}
{
  level: 'error',
  message: null,
  service: 'user-service',
  timestamp: '2021-12-11T15:53:37.155Z'
}
{
  level: 'error',
  message: null,
  service: 'user-service',
  timestamp: '2021-12-11T15:53:37.170Z'
}
{
  level: 'error',
  message: null,
  service: 'user-service',
  timestamp: '2021-12-11T15:53:37.172Z'
}
{
  level: 'error',
  message: Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-1639238144896
              (File_ID INT NOT NULL AUTO_INCREMENT,  
              F' at line 1
      at Packet.asError (C:\Users\DELL\Desktop\New folder (4)\AdvancedSeE\dbmanager\node_modules\mysql2\lib\packets\packet.js:728:17)
      at Query.execute (C:\Users\DELL\Desktop\New folder (4)\AdvancedSeE\dbmanager\node_modules\mysql2\lib\commands\command.js:29:26)
      at Connection.handlePacket (C:\Users\DELL\Desktop\New folder (4)\AdvancedSeE\dbmanager\node_modules\mysql2\lib\connection.js:456:32)
      at PacketParser.onPacket (C:\Users\DELL\Desktop\New folder (4)\AdvancedSeE\dbmanager\node_modules\mysql2\lib\connection.js:85:12)
      at PacketParser.executeStart (C:\Users\DELL\Desktop\New folder (4)\AdvancedSeE\dbmanager\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (C:\Users\DELL\Desktop\New folder (4)\AdvancedSeE\dbmanager\node_modules\mysql2\lib\connection.js:92:25)
      at Socket.emit (node:events:329:20)
      at addChunk (node:internal/streams/readable:304:12)
      at readableAddChunk (node:internal/streams/readable:279:9)
      at Socket.Readable.push (node:internal/streams/readable:218:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:192:23) {
    code: 'ER_PARSE_ERROR',
    errno: 1064,
    sqlState: '42000',
    sqlMessage: "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-1639238144896\n" +
      '            (File_ID INT NOT NULL AUTO_INCREMENT,  \n' +
      "            F' at line 1",
    sql: 'CREATE TABLE uploadfile-1639238144896\n' +
      '            (File_ID INT NOT NULL AUTO_INCREMENT,  \n' +
      '            File_Name VARCHAR(50),\n' +
      '            PRIMARY KEY(File_ID)\n' +
      '            )'
  },
  service: 'user-service',
  timestamp: '2021-12-11T15:55:45.324Z'
}
{
  level: 'error',
  message: null,
  service: 'user-service',
  timestamp: '2021-12-11T16:01:08.570Z'
}
{
  level: 'error',
  message: null,
  service: 'user-service',
  timestamp: '2021-12-11T16:01:08.584Z'
}
{
  level: 'error',
  message: null,
  service: 'user-service',
  timestamp: '2021-12-11T16:01:08.586Z'
}
{
  level: 'error',
  message: Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-1639238482733
              (File_ID INT NOT NULL AUTO_INCREMENT,  
              F' at line 1
      at Packet.asError (C:\Users\DELL\Desktop\New folder (4)\AdvancedSeE\dbmanager\node_modules\mysql2\lib\packets\packet.js:728:17)
      at Query.execute (C:\Users\DELL\Desktop\New folder (4)\AdvancedSeE\dbmanager\node_modules\mysql2\lib\commands\command.js:29:26)
      at Connection.handlePacket (C:\Users\DELL\Desktop\New folder (4)\AdvancedSeE\dbmanager\node_modules\mysql2\lib\connection.js:456:32)
      at PacketParser.onPacket (C:\Users\DELL\Desktop\New folder (4)\AdvancedSeE\dbmanager\node_modules\mysql2\lib\connection.js:85:12)
      at PacketParser.executeStart (C:\Users\DELL\Desktop\New folder (4)\AdvancedSeE\dbmanager\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (C:\Users\DELL\Desktop\New folder (4)\AdvancedSeE\dbmanager\node_modules\mysql2\lib\connection.js:92:25)
      at Socket.emit (node:events:329:20)
      at addChunk (node:internal/streams/readable:304:12)
      at readableAddChunk (node:internal/streams/readable:279:9)
      at Socket.Readable.push (node:internal/streams/readable:218:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:192:23) {
    code: 'ER_PARSE_ERROR',
    errno: 1064,
    sqlState: '42000',
    sqlMessage: "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-1639238482733\n" +
      '            (File_ID INT NOT NULL AUTO_INCREMENT,  \n' +
      "            F' at line 1",
    sql: 'CREATE TABLE uploadfile-1639238482733\n' +
      '            (File_ID INT NOT NULL AUTO_INCREMENT,  \n' +
      '            File_Name VARCHAR(50),\n' +
      '            PRIMARY KEY(File_ID)\n' +
      '            )'
  },
  service: 'user-service',
  timestamp: '2021-12-11T16:01:22.874Z'
}
{
  level: 'error',
  message: null,
  service: 'user-service',
  timestamp: '2021-12-11T16:11:47.977Z'
}
{
  level: 'error',
  message: null,
  service: 'user-service',
  timestamp: '2021-12-11T16:11:47.981Z'
}
{
  level: 'error',
  message: null,
  service: 'user-service',
  timestamp: '2021-12-11T16:11:47.982Z'
}
{
  level: 'error',
  message: Error: Access denied for user 'root'@'localhost' (using password: YES)
      at Packet.asError (C:\Users\IAmour\Desktop\lk\AdvancedSeE\dbmanager\node_modules\mysql2\lib\packets\packet.js:728:17)
      at ClientHandshake.execute (C:\Users\IAmour\Desktop\lk\AdvancedSeE\dbmanager\node_modules\mysql2\lib\commands\command.js:29:26)
      at Connection.handlePacket (C:\Users\IAmour\Desktop\lk\AdvancedSeE\dbmanager\node_modules\mysql2\lib\connection.js:456:32)
      at PacketParser.onPacket (C:\Users\IAmour\Desktop\lk\AdvancedSeE\dbmanager\node_modules\mysql2\lib\connection.js:85:12)
      at PacketParser.executeStart (C:\Users\IAmour\Desktop\lk\AdvancedSeE\dbmanager\node_modules\mysql2\lib\packet_parser.js:75:16)
      at Socket.<anonymous> (C:\Users\IAmour\Desktop\lk\AdvancedSeE\dbmanager\node_modules\mysql2\lib\connection.js:92:25)
      at Socket.emit (events.js:315:20)
      at addChunk (internal/streams/readable.js:309:12)
      at readableAddChunk (internal/streams/readable.js:284:9)
      at Socket.Readable.push (internal/streams/readable.js:223:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
    code: 'ER_ACCESS_DENIED_ERROR',
    errno: 1045,
    sqlState: '28000',
    sqlMessage: "Access denied for user 'root'@'localhost' (using password: YES)",
    sql: undefined
  },
  service: 'user-service',
  timestamp: '2021-12-13T20:10:29.883Z'
  message: Error: connect ETIMEDOUT
      at Connection._handleTimeoutError (C:\Users\DELL\Desktop\New folder (4)\AdvancedSeE\dbmanager\node_modules\mysql2\lib\connection.js:189:17)
      at listOnTimeout (node:internal/timers:556:17)
      at processTimers (node:internal/timers:499:7) {
    errorno: 'ETIMEDOUT',
    code: 'ETIMEDOUT',
    syscall: 'connect',
    fatal: true
  },
  service: 'user-service',
  timestamp: '2021-12-13T21:00:44.759Z'
}
{
  level: 'error',
  message: Error: connect ETIMEDOUT
      at Connection._handleTimeoutError (C:\Users\DELL\Desktop\New folder (4)\AdvancedSeE\dbmanager\node_modules\mysql2\lib\connection.js:189:17)
      at listOnTimeout (node:internal/timers:556:17)
      at processTimers (node:internal/timers:499:7) {
    errorno: 'ETIMEDOUT',
    code: 'ETIMEDOUT',
    syscall: 'connect',
    fatal: true
  },
  service: 'user-service',
  timestamp: '2021-12-13T21:00:44.765Z'
}
{
  level: 'error',
  message: Error: connect ETIMEDOUT
      at Connection._handleTimeoutError (C:\Users\DELL\Desktop\New folder (4)\AdvancedSeE\dbmanager\node_modules\mysql2\lib\connection.js:189:17)
      at listOnTimeout (node:internal/timers:556:17)
      at processTimers (node:internal/timers:499:7) {
    errorno: 'ETIMEDOUT',
    code: 'ETIMEDOUT',
    syscall: 'connect',
    fatal: true
  },
  service: 'user-service',
  timestamp: '2021-12-13T21:00:44.767Z'
}
{
  level: 'error',
  message: Error: connect ETIMEDOUT
      at Connection._handleTimeoutError (C:\Users\DELL\Desktop\New folder (4)\AdvancedSeE\dbmanager\node_modules\mysql2\lib\connection.js:189:17)
      at listOnTimeout (node:internal/timers:556:17)
      at processTimers (node:internal/timers:499:7) {
    errorno: 'ETIMEDOUT',
    code: 'ETIMEDOUT',
    syscall: 'connect',
    fatal: true
  },
  service: 'user-service',
  timestamp: '2021-12-13T21:08:29.213Z'
}
{
  level: 'error',
  message: Error: connect ETIMEDOUT
      at Connection._handleTimeoutError (C:\Users\DELL\Desktop\New folder (4)\AdvancedSeE\dbmanager\node_modules\mysql2\lib\connection.js:189:17)
      at listOnTimeout (node:internal/timers:556:17)
      at processTimers (node:internal/timers:499:7) {
    errorno: 'ETIMEDOUT',
    code: 'ETIMEDOUT',
    syscall: 'connect',
    fatal: true
  },
  service: 'user-service',
  timestamp: '2021-12-13T21:08:29.216Z'
}

